-- ============================================================================
--  MIGRACIÓN COMPLETA: Bump Comba | Flixthor  EN CASO DE QUE QUIERA MIGRAR AHI ESTA DISPONIBLE TODO
--  Ejecutar en el SQL Editor del proyecto NUEVO de Supabase.
--  Orden: 1) Tablas, 2) Índices, 3) Funciones, 4) Triggers, 5) RLS, 6) Datos
-- ============================================================================

-- ════════════════════════════════════════════════════════════════════════════
-- 1) TABLAS
-- ════════════════════════════════════════════════════════════════════════════

CREATE TABLE public.admin_users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  role text NOT NULL DEFAULT 'collaborator'::text
    CHECK (role = ANY (ARRAY['admin'::text, 'collaborator'::text])),
  created_at timestamptz DEFAULT now(),
  last_login timestamptz
);

CREATE TABLE public.sys_config (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  value text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  description text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.m3u_load_balancer (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL,
  value text NOT NULL,
  current_connections integer DEFAULT 0,
  max_connections integer DEFAULT 1000,
  is_active boolean DEFAULT true,
  name text,
  created_at timestamptz DEFAULT now(),
  type text DEFAULT 'm3u'::text,
  username text,
  password text
);

CREATE TABLE public.custom_content (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  video_url text,
  thumbnail_url text,
  type text NOT NULL CHECK (type = ANY (ARRAY['movie'::text, 'series'::text, 'episode'::text])),
  parent_id uuid REFERENCES public.custom_content(id) ON DELETE CASCADE,
  category text NOT NULL DEFAULT 'Recomendados'::text,
  season integer,
  episode integer,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  title_aliases text[],
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.home_banners (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  image_url text NOT NULL,
  content_url text NOT NULL,
  title text,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  tab text NOT NULL DEFAULT 'Inicio'::text
);

CREATE TABLE public.content_likes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url text NOT NULL,
  name text NOT NULL,
  category text NOT NULL,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.content_reports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  content_name text NOT NULL,
  category text NOT NULL,
  url text NOT NULL,
  reason text NOT NULL,
  device_id text,
  status text DEFAULT 'pending'::text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.content_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  details text,
  status text NOT NULL DEFAULT 'pending'::text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.tv_devices (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_ref text NOT NULL,
  user_kind text NOT NULL DEFAULT 'revenuecat'::text,
  device_id text NOT NULL,
  device_name text,
  device_token text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz,
  revoked_at timestamptz,
  sources text
);

CREATE TABLE public.tv_pairings (
  code text PRIMARY KEY,
  device_id text NOT NULL,
  device_name text,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  claimed_at timestamptz,
  claimed_by text,
  device_token text,
  attempts integer NOT NULL DEFAULT 0
);

-- ════════════════════════════════════════════════════════════════════════════
-- 2) ÍNDICES
-- ════════════════════════════════════════════════════════════════════════════

CREATE UNIQUE INDEX custom_content_series_title_unique
  ON public.custom_content (title) WHERE (type = 'series'::text);

CREATE INDEX custom_content_updated_at_idx
  ON public.custom_content (updated_at DESC);

CREATE INDEX idx_custom_content_active_id
  ON public.custom_content (is_active, id);

CREATE UNIQUE INDEX custom_content_parent_id_season_episode_key
  ON public.custom_content (parent_id, season, episode);

CREATE INDEX idx_m3u_lb_code
  ON public.m3u_load_balancer (key);

CREATE INDEX idx_m3u_load_balancer_key
  ON public.m3u_load_balancer (key) WHERE (is_active = true);

CREATE INDEX tv_devices_token
  ON public.tv_devices (device_token) WHERE (revoked_at IS NULL);

CREATE INDEX tv_devices_user_activos
  ON public.tv_devices (user_ref) WHERE (revoked_at IS NULL);

CREATE UNIQUE INDEX tv_devices_user_ref_device_id_key
  ON public.tv_devices (user_ref, device_id);

CREATE INDEX tv_pairings_caducidad
  ON public.tv_pairings (expires_at);

-- ════════════════════════════════════════════════════════════════════════════
-- 3) FUNCIONES
-- ════════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.custom_content_marcar_edicion()
  RETURNS trigger LANGUAGE plpgsql AS $$
begin
  new.updated_at = now();
  return new;
end;
$$;

CREATE OR REPLACE FUNCTION public.increment_m3u_connections(target_id uuid)
  RETURNS void LANGUAGE plpgsql
  SECURITY DEFINER SET search_path TO 'public', 'pg_temp' AS $$
begin
  update public.m3u_load_balancer
     set current_connections = coalesce(current_connections, 0) + 1
   where id = target_id;
end;
$$;

CREATE OR REPLACE FUNCTION public.limpiar_thumb_episodio()
  RETURNS trigger LANGUAGE plpgsql AS $$
begin
  if new.type = 'episode' and new.thumbnail_url is not null
     and exists (select 1 from public.custom_content p
                  where p.id = new.parent_id and p.thumbnail_url is not null)
  then
    new.thumbnail_url := null;
  end if;
  return new;
end;
$$;

CREATE OR REPLACE FUNCTION public.limpiar_thumbs_de_la_serie()
  RETURNS trigger LANGUAGE plpgsql AS $$
begin
  if new.type = 'series' and new.thumbnail_url is not null then
    update public.custom_content
       set thumbnail_url = null
     where parent_id = new.id
       and type = 'episode'
       and thumbnail_url is not null;
  end if;
  return null;
end;
$$;

CREATE OR REPLACE FUNCTION public.limpiar_tv_pairings()
  RETURNS void LANGUAGE sql
  SECURITY DEFINER SET search_path TO 'public' AS $$
  delete from public.tv_pairings
   where expires_at < now() - interval '1 hour';
$$;

-- ════════════════════════════════════════════════════════════════════════════
-- 4) TRIGGERS
-- ════════════════════════════════════════════════════════════════════════════

CREATE TRIGGER custom_content_set_updated_at
  BEFORE UPDATE ON public.custom_content
  FOR EACH ROW EXECUTE FUNCTION custom_content_marcar_edicion();

CREATE TRIGGER trg_limpiar_thumb_episodio
  BEFORE INSERT OR UPDATE ON public.custom_content
  FOR EACH ROW EXECUTE FUNCTION limpiar_thumb_episodio();

CREATE TRIGGER trg_limpiar_thumbs_de_la_serie
  AFTER INSERT OR UPDATE ON public.custom_content
  FOR EACH ROW EXECUTE FUNCTION limpiar_thumbs_de_la_serie();

-- ════════════════════════════════════════════════════════════════════════════
-- 5) RLS (Row Level Security)
-- ════════════════════════════════════════════════════════════════════════════

ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow select for login" ON public.admin_users FOR SELECT TO public USING (true);
CREATE POLICY "Admin insert admin_users" ON public.admin_users FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Admin update admin_users" ON public.admin_users FOR UPDATE TO public USING (true) WITH CHECK (true);
CREATE POLICY "Admin delete admin_users" ON public.admin_users FOR DELETE TO public USING (true);

ALTER TABLE public.sys_config ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access to sys_config" ON public.sys_config FOR ALL TO public USING (true) WITH CHECK (true);

ALTER TABLE public.m3u_load_balancer ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access to m3u_load_balancer" ON public.m3u_load_balancer FOR ALL TO public USING (true) WITH CHECK (true);

ALTER TABLE public.custom_content ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access to custom_content" ON public.custom_content FOR ALL TO public USING (true) WITH CHECK (true);

ALTER TABLE public.home_banners ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow full access to home_banners" ON public.home_banners FOR ALL TO public USING (true) WITH CHECK (true);

ALTER TABLE public.content_likes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public select" ON public.content_likes FOR SELECT TO public USING (true);
CREATE POLICY "Allow public insert" ON public.content_likes FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Admin update content_likes" ON public.content_likes FOR UPDATE TO public USING (true) WITH CHECK (true);
CREATE POLICY "Admin delete content_likes" ON public.content_likes FOR DELETE TO public USING (true);

ALTER TABLE public.content_reports ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public to insert reports" ON public.content_reports FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Allow public select from content_reports" ON public.content_reports FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public update to content_reports" ON public.content_reports FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow public delete from content_reports" ON public.content_reports FOR DELETE TO anon, authenticated USING (true);
CREATE POLICY "Enable read access for service role only" ON public.content_reports FOR ALL TO service_role USING (true);

ALTER TABLE public.content_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public insert to content_requests" ON public.content_requests FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Allow public select from content_requests" ON public.content_requests FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public update to content_requests" ON public.content_requests FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow public delete from content_requests" ON public.content_requests FOR DELETE TO anon, authenticated USING (true);

ALTER TABLE public.tv_devices ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.tv_pairings ENABLE ROW LEVEL SECURITY;

-- ════════════════════════════════════════════════════════════════════════════
-- 6) DATOS DE TABLAS PEQUEÑAS
--    (custom_content se importa aparte por su tamaño — ver instrucciones)
-- ════════════════════════════════════════════════════════════════════════════

-- sys_config
INSERT INTO public.sys_config (id, key, value, is_active, description, created_at, updated_at) VALUES
  ('3c060649-5d4a-45b5-bb01-e26b0bdd3919', 'allow_content_requests', 'true', true,
   'Permite o deshabilita la opción de pedir películas/series en el buscador',
   '2026-08-07T03:03:00.68086+00:00', '2026-08-07T03:03:00.68086+00:00'),
  ('12b8deaf-c9a9-4e40-8806-e8e1152749f2', 'turbo_max_parallel', '2', true,
   'Conexiones simultaneas del reproductor contra el servidor del proveedor',
   '2026-08-16T19:44:48.645791+00:00', '2026-08-17T01:13:21.391454+00:00');

-- m3u_load_balancer (solo las activas)
INSERT INTO public.m3u_load_balancer (id, key, value, current_connections, max_connections, is_active, name, created_at, type, username, password) VALUES
  ('51f30892-4447-4249-a67e-62b34cec5583', '1234',
   'https://drive.google.com/uc?export=download&id=1IQuTKacd8bgW6xIEyKzjVG4WB11nRJ9r',
   0, 1000, true, 'Google Drive Server', '2026-08-03T15:08:29.734561+00:00', 'm3u', null, null),
  ('4af3c25c-a3d4-4a7b-9586-7c78945e5a40', '5', 'http://217.216.80.212',
   0, 1000, true, 'Test Playlist 4', '2026-08-16T20:56:18.062072+00:00', 'xtream', 'VyzxnRjzJf', 'MHWBnbCe68'),
  ('68828cd0-dc0b-46ad-b157-fbc174b64dbc', '5', 'http://217.216.80.212',
   0, 1000, true, 'Test Playlist 6', '2026-03-07T23:57:35.880489+00:00', 'xtream', 'jZc22GJJuq', 'wuG8jr2X6q'),
  ('69d98be3-69c0-46c8-ab93-8a9b67f6cd00', '5', 'http://217.216.80.212',
   0, 1000, true, 'Test Playlist 7', '2026-02-27T18:20:18+00:00', 'xtream', '5BTUXxEqsp', 'EDdRMz4tqv');

-- ════════════════════════════════════════════════════════════════════════════
-- FIN — Ahora importa custom_content y configura las Edge Functions
-- ════════════════════════════════════════════════════════════════════════════
