class ContentFilters {
  static const List<String> excludedCountries = [
    'arabia',
    'argentina',
    'australia',
    'austria',
    'alemania',
    'brasil',
    'belgium',
    'bolivia',
    'bulgaria',
    'canada',
    'chile',
    'china',
    'colombia',
    'costa rica',
    'cuba',
    'croacia',
    'dinamarca',
    'dominicana',
    'ecuador',
    'egipto',
    'españa',
    'estados unidos',
    'filipinas',
    'finlandia',
    'francia',
    'grecia',
    'guatemala',
    'holanda',
    'honduras',
    'hungria',
    'india',
    'indonesia',
    'iran',
    'iraq',
    'irlanda',
    'israel',
    'italia',
    'japon',
    'jordania',
    'korea',
    'kuwait',
    'libano',
    'libia',
    'marruecos',
    'mexico',
    'myanmar',
    'nicaragua',
    'nigeria',
    'noruega',
    'pakistan',
    'panama',
    'paraguay',
    'peru',
    'polonia',
    'portugal',
    'puerto rico',
    'qatar',
    'republica',
    'romania',
    'rusia',
    'salvador',
    'serbia',
    'singapur',
    'siria',
    'suecia',
    'suiza',
    'tailandia',
    'taiwan',
    'tunisia',
    'turquia',
    'ucrania',
    'uk',
    'uruguay',
    'usa',
    'venezuela',
    'vietnam',
    'yemen',
  ];

  static const List<String> excludedKeywords = [
    'apostarias',
    'adulto',
    'adultos',
    'xxx',
    '+18',
    '18+',
    '24/7',
    '24 7',
    '24-7',
    'canales exclusivos',
    'exclusivo',
    'en vivo',
    'live',
    'tv en vivo',
    'canales',
    'channel',
    'deportes',
    'sport',
    'futbol',
    'football',
    'eventos deportivos',
    'evento',
    'liga',
    'streaming',
    'gratis',
    'free tv',
    'test',
    'ppv',
    'lucha libre',
    'religion',
    'noticias',
    'news',
    'radio',
    'novela',
    'variedad',
    'uhd',
    'broadcast',
    'directo',
  ];

  static const List<String> seriesExclusions = [
    'novela',
    'noticia',
    'variedad',
    'deporte',
    'canales',
    'live',
    'uhd',
  ];

  static const List<Map<String, dynamic>> curatedSeriesSections = [
    {
      'title': 'Drama Coreano',
      'keywords': ['corea', 'korean', 'k-drama', 'kdrama', 'doramas coreanos'],
    },
    {
      'title': 'Drama Tailandés',
      'keywords': ['tailand', 'thai', 'lakorns'],
    },
    {
      'title': 'Romántico',
      'keywords': ['romantic', 'romantico', 'romance', 'amor'],
    },
    {
      'title': 'Anime',
      'keywords': ['anime', 'animacion japonesa', 'animes'],
    },
    {
      'title': 'Comedia',
      'keywords': ['comedia', 'comedy', 'humor', 'sitcom'],
    },
    {
      'title': 'Drama',
      'keywords': ['drama'],
    },
    {
      'title': 'Aventura',
      'keywords': ['aventura', 'adventure', 'accion'],
    },
    {
      'title': 'Terror',
      'keywords': ['terror', 'horror', 'miedo', 'suspenso'],
    },
    {
      'title': 'Ciencia Ficción',
      'keywords': [
        'ciencia ficcion',
        'sci-fi',
        'scifi',
        'science fiction',
        'ficcion',
      ],
    },
    {
      'title': 'Guerra',
      'keywords': ['guerra', 'war', 'militar', 'belica'],
    },
  ];

  static const List<Map<String, dynamic>> curatedNovelaSections = [
    {
      'title': 'Telenovelas Mexicanas',
      'keywords': ['mexican', 'mexico', 'televisa', 'azteca', 'mexicana'],
    },
    {
      'title': 'Telenovelas Colombianas',
      'keywords': ['colombian', 'colombia', 'rcn', 'caracol', 'colombiana'],
    },
    {
      'title': 'Novelas Españolas',
      'keywords': ['españa', 'spanish', 'española', 'espanola', 'rtve'],
    },
    {
      'title': 'Popular',
      'keywords': ['popular', 'top', 'mejor', 'exito', 'hit'],
    },
    {
      'title': 'Novelas Turcas',
      'keywords': ['turca', 'turco', 'turkish', 'turquia', 'turkey'],
    },
    {
      'title': 'Reality Shows',
      'keywords': ['reality', 'show', 'concurso', 'talent', 'competencia'],
    },
    {
      'title': 'Novelas Americanas',
      'keywords': ['americana', 'american', 'usa', 'estados unidos', 'gringa'],
    },
  ];

  static const List<Map<String, dynamic>> curatedAnimationSections = [
    {
      'title': 'Anime',
      'keywords': ['anime', 'animes', 'animacion japonesa', 'japanese animation'],
    },
    {
      'title': 'Disney & Pixar',
      'keywords': ['disney', 'pixar', 'walt disney'],
    },
    {
      'title': 'Caricaturas Clásicas',
      'keywords': ['cartoon', 'caricatura', 'looney', 'tom y jerry', 'scooby', 'hanna barbera'],
    },
    {
      'title': 'Anime de Acción',
      'keywords': ['dragon ball', 'naruto', 'one piece', 'bleach', 'attack on titan', 'shingeki', 'demon slayer', 'kimetsu', 'jujutsu'],
    },
    {
      'title': 'Para Niños',
      'keywords': ['kids', 'infantil', 'nickelodeon', 'nick', 'paw patrol', 'peppa', 'bob esponja', 'spongebob', 'dora'],
    },
    {
      'title': 'Películas Animadas',
      'keywords': ['animada', 'animado', 'animated', 'animation', 'dreamworks', 'illumination', 'ghibli', 'studio ghibli'],
    },
    {
      'title': 'Anime Romántico',
      'keywords': ['romance', 'romantico', 'love', 'shoujo', 'shojo'],
    },
    {
      'title': 'Superhéroes Animados',
      'keywords': ['marvel', 'dc', 'superman', 'batman', 'spider', 'avenger', 'hero', 'heroe'],
    },
  ];
}
